### ISSUE TITLE
Is it possible to use the CEC module database?

### ISSUE THREAD

**Issue by gplssm** [oemof/feedinlib#10]
@uvchik

**Comment by uvchik** [comment]
It seems not to work. We should enable this.

**Comment by uvchik** [comment]
With commit 84a4383 it is possible to access the cec-module-library but they seem to have different parameters. You should create a pvlib-issue for that.

**Comment by uvchik** [comment]
See issue [22](../../../pvlib/pvlib-python/issues/122) of the pvlib.

**Comment by uvchik** [comment]
With commit fda2a93b I removed the access to the cec-module-library again, because it will not work with the feedinlib as the pv-model is designed right now.
