### ISSUE TITLE
Inspect low wind generation at 'brandenkopf'

### ISSUE THREAD

**Issue by gplssm** [oemof/feedinlib#11]
Generation is near half of reference data which is at around 2000 flhs, see #6.

**Comment by uvchik** [comment]
I do not know 'brandenkopf' but it might be a problem with the the weather data set. The weather data of coasdat2 has a raster of 0.22 degree. If 'brandenkopf' is a region where the wind speed is very inhomogeneous, the wind speed at a good wind site might be to low. If the yield at all reference regions is to low, there might be a systematic error in the wind model.
