### ISSUE TITLE
Module name look-up table

### ISSUE THREAD

**Issue by gplssm** [oemof/feedinlib#12]
According to #6 it is quite nasty to get the right name of modules in the sandia modules database. Create a look-up table in some accessible way...

**Comment by uvchik** [comment]
With commit d44cb69 it is now possible to get the full list:

```python
from feedinlib import models
# get all modules
all_modules = models.PvlibBased().fetch_module_data(module_name='all')

# write out the keys from 'Yingli'
for module in all_modules.keys():
    if 'Yingli' in module:
        print(module)
```

**Comment by uvchik** [comment]
@gplssm : If it works for you, you can close this issue.

**Comment by gplssm** [comment]
Nicy nice! Works perfectly fine for me :)
