### ISSUE TITLE
webco about the future of the feedinlib

### ISSUE THREAD

**Issue by birgits** [oemof/feedinlib#28]
@gnn and @uvchik it would be good to have a webco where we discuss the future of the feedinlib soon. Would any time next week on Wednesday, Thursday or Friday work for you?

**Comment by uvchik** [comment]
From 10 to 15 and from 16.30 to 18.30 on Wednesday, Thursday or Friday.

**Comment by birgits** [comment]
@uvchik I just talked to gnn on the phone about a webco date. Would next Wednesday afternoon work for you?

**Comment by uvchik** [comment]
Okay, Wednesday from 14.00 to 15.00 will be okay. If we need more time we can meet again in the later afternoon, but I guess one hour is far enough.

**Comment by birgits** [comment]
Links from webco:
https://www.researchgate.net/post/Does_any_one_have_a_script_in_r_or_python_to_pull_Merra_data
https://github.com/Unidata/netcdf4-python
http://www.geomar.de/mitarbeiter/fb1/me/jharlass/wrf/erai/

**Comment by gnn** [comment]
These are the minutes I wrote down during our WebCo:

#### 2017-06-14: Feedinlib quo vadis

  - Einheitliches Wetterobjekt
    - Einheitliche/Standardisierte Namen für Messreien
    - PVlib/Windpowerlib: Dataframes
  - Anschluß an Wetterdatensatz
  - Einheitliche Schnittstelle für techn. spezialisierte Bibliotheken (e.g.: pvlib, windpowerlib)
  - JanUrb? MERRA online API?

They're only here for historical reasons as I translated them to English and converted them to the roadmap written down in #29.

**Comment by birgits** [comment]
@gnn did we decide to close this issue? I'm not sure if you wanted to add some documentation before closing it.
