### ISSUE TITLE
Quo Vadis? Roadmap as of 2017-06-14.

### ISSUE THREAD

**Issue by gnn** [oemof/feedinlib#29]
The feedinlib as of version 0.0.11 will receive an API breaking overhaul. As version 0.0.11 is dysfunctional when installed as a package, we will release a last version 0.0.12 that is at least working. After that we'll move to 0.1.x and initially focus on developing the following features:

  - a standardized/unified 'weather' object containing:
    - standardized names for measured variables and
    - the ability to convert itself to `pvlib` and `windpowerlib` compatible `dataframe`s;
  - easy access to at least one freely available weather dataset and
  - if possible a unified interface to access functionality of technically more specialized libraries like `pvlib`
    and `windpowerlib`.

**Comment by uvchik** [comment]
The next step is the release of v0.1.0 (#64)
