### ISSUE TITLE
Test the feedinlib

### ISSUE THREAD

**Issue by uvchik** [oemof/feedinlib#3]
Test the feedinlib and report bugs.

**Comment by gplssm** [comment]
Did full load hour (flh) calculations for 1 PV and two types of wind power plants at 3 sites

## Berlin (E: 13.5, N: 52.5)
power plant | flh
--------------- | ---
PV (Yingli) | 1142.28457566
Wind (E126) | 1678.75911836
Wind (E101) | 2417.67331292

## Glücksburg (E: 9.603068, N: 54.873547)
power plant | flh
--------------- | ---
PV (Yingli) | 1122.49038653
Wind (E126) | 2386.66056067
Wind (E101) | 3267.14634494

## Würzburg (E: 9.957438, N: 49.804585)
power plant | flh
--------------- | ---
PV (Yingli) | 1180.91134302
Wind (E126) | 1281.0501327
Wind (E101) | 1859.85708164

Flh of PV seem a bit too high, but I don't have proper reference values. Wind Flh could overestimated as well (same issues, no reference).

Created an issue #6 for the first review of generation/ flh data.
