### ISSUE TITLE
weather data time series for wind won't load - Feedinlib/pandas bug

### ISSUE THREAD

**Issue by justinhodura** [oemof/feedinlib#54]
Hello,

at the beginning of the week there was a problem with the oep-api, which seems to be fixed by now. 
Apperently, I have another issue, which seems to be a bug.
I use the feedinlib version 0.1.0rc4.

![grafik](https://user-images.githubusercontent.com/77781675/105348053-0cc96e80-5be8-11eb-8968-ec0b65127f51.png)
![grafik](https://user-images.githubusercontent.com/77781675/105348540-c4f71700-5be8-11eb-83bc-54a934cbc00e.png)

I am trying to generate a wind time series, using open_FRED_weather_windpowerlib.

The error is shown in the txt file:
[github.txt](https://github.com/oemof/feedinlib/files/5849046/github.txt)

Thank you for the help!

**Comment by SabineHaas** [comment]
Hey, thanks for reporting!
Your code seems to run through fine, you only get a `FutureWarning`, so nothing to worry about for you now.
