### ISSUE TITLE
Define unit of 'installed_capacity' and `peak_power`

### ISSUE THREAD

**Issue by gplssm** [oemof/feedinlib#8]
Units of `installed_capacity` in https://github.com/oemof/feedinlib/blob/master/example/feedinlib_example.py#L117 and `peak_power` in https://github.com/oemof/feedinlib/blob/master/example/feedinlib_example.py#L136 are not defined

**Comment by uvchik** [comment]
It depends on the units of the weather data set and the units of the turbine parameters.

But you are right, somehow we have to deal with units. I will think about it.

**Comment by uvchik** [comment]
I think its more a documentation issue than a bug.

**Comment by uvchik** [comment]
I mixed this issue with #5. Commit dafd43 solved issue #5 and not this one. I will reopen it.
